### ISSUE TITLE
Replicate data?

### ISSUE THREAD

**Issue by xiulinyang** [SaminFakharian/Contextualized-Embeddings-Encode-Monolingual-and-Cross-lingual-Knowledge-of-Idiomaticity#1]
Hi thank you very much for this dataset. I checked the test and train dataset and it seems the naming of the file does not follow what you said in the paper and the sentences in each data split overlap with each other. May I know if you did this on purpose? Thank you!

**Comment by SaminFakharian** [comment]
Hi, thanks for mentioning this. For each dataset, please use the filename "0." I have added the TEST datasets to the repository to facilitate your access and replicate results. As stated in the paper, DEV and TEST expressions do not overlap. I hope this clarification is helpful.
